import os


class APP_CONFIG:
    SECRET_KEY = os.getenv("FLASK_SECRET_KEY")
    DEBUG = bool(os.getenv("DEBUG"))

    SQLALCHEMY_DATABASE_URI = os.getenv("POSTGRES_URI_STRING")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SECURE=True,  # Set To True in production (HTTPS)
    SESSION_COOKIE_SAMESITE="Lax"
